### ISSUE TITLE
Catch all exceptions when iterating over entries and comments, both ways.  Skip and log the problem at the entry level, then continue with the sync

### ISSUE THREAD

**Issue by megahirt** [sillsdev/LfMerge#232]
This task is all about making LFMerge more robust by reducing the number of projects on HOLD.  Any exception that occurs while in the entry or comment loop within either TransferMongoToLcm or TransferLcmToMongo should be handled by

- log the exception error to the state file
- skip the entry or comment and carry on with the next

Additional information about exception handling should now be kept the sync state file.  I propose the following changes to the state file:

Remove "ErrorMessage" in favor of an "Error" object with multiple properties.
Behavior:
- If no exceptions are thrown in a LfMerge sync, the Error object is discarded and the state is set to IDLE
- If an exception is thrown in a place other than the looping over entries / comments, the exceptionMessage is filled out and the state changes to HOLD.
- LFMerge will catch all exceptions inside the loops over entries and comments and log the error messages, as well as metadata about the comment/entry which failed to sync.  Skip the failed entry and increment the skip counter.  The sync will finish with a log of errors available to the user, and the state is set back to IDLE

- the proposed Error object looks like this ([also attached as a json file for easy copy/paste](https://github.com/sillsdev/LfMerge/files/8674141/lfmerge.error.sample.json.txt)):
```
{
  "Error": {
    "timestamp": "timestamp of when the exception occurred (or in the case of skipped entries/comments) the time when processing finished",
    "exceptionMessage": "string of global error message that occurred (not while looping entries/comments)",
    "skipped": {
      "toMongo": {
        "entries": {
          "count": 5,
          "list": [
            {
              "guid": "FW GUID",
              "id": "MongoId",
              "exceptionMessage": "message",
              "label": "string representing the entry - probably lexeme first non empty WS. 100 character limit"
            }
          ]
        },
        "comments": {
          "count": 3,
          "list": [
            {
              "guid": "FW GUID",
              "id": "MongoId",
              "exceptionMessage": "message",
              "label": "string representing the comment- 100 char limit",
              "entry": {
                "guid": "FW GUID",
                "id": "MongoId",
                "label": "string representing the comment- 100 char limit"
              }
            }
          ]
        }
      },
      "toLcm": {
        "entries": {
          "count": 5,
          "list": [
            {
              "guid": "FW GUID",
              "id": "MongoId",
              "exceptionMessage": "message",
              "label": "string representing the entry - probably lexeme first non empty WS. 100 character limit"
            }
          ]
        },
        "comments": {
          "count": 3,
          "list": [
            {
              "guid": "FW GUID",
              "id": "MongoId",
              "exceptionMessage": "message",
              "label": "string representing the comment- 100 char limit",
              "entry": {
                "guid": "FW GUID",
                "id": "MongoId",
                "label": "string representing the comment- 100 char limit"
              }
            }
          ]
        }
      }
    }
  }
}

```

**Comment by rmunn** [comment]
I'll have to think about this one. My first thought was that this could have data-integrity implications because we'd be doing partial updates, where some entries did not get sent to the server, instead of full updates. But since we can report the failed entries to the user, that's probably okay.

**Comment by rmunn** [comment]
Another minor thought is that the 100 character limit needs to be handled carefully. With UTF-8 text, you can't just chop a string at 97 characters and add "..." to it. You have to check if the byte you're discarding has binary form `10xxxxxx` (e.g., in the `8x` through `bx` range in hex), and if so, rewind until the first byte that does not land in the `8x-bx` range. That ensures that you're not truncating a UTF-8 string in the middle of a multi-byte sequence and creating invalid UTF-8. But that's a pretty simple algorithm, and it will be pretty easy to write a `trimUtf8` function. So I'll leave this comment around so that when I implement this idea later on, I won't forget about trimming UTF-8 correctly.

**Comment by rmunn** [comment]
Further thoughts: if the skip counter gets too large (say, 25 entries), then abort the whole update and report to the user that there were lots of errors, here's the first 25. We don't want the user to feel overwhelmed if his project with 1,000 entries has the same error in every entry. Still don't put the project on hold, but don't send a partial update to Language Depot if there were more than 25 errors.

**Comment by rmunn** [comment]
Started working on this today, and found another design issue that needs to be thought through.

Currently, we sync all the entries, *then* sync the comments as a separate step; the comments are in a different file (`*.ChorusNotes`) in FLEx, so that makes sense. But if there was a comment on an entry that failed to sync, it does make it difficult to skip those comments. (Which is probably necessary, otherwise it would be possible to end up with a comment referring to entries that aren't there, or all kinds of other weird situations). The ConvertLcmToMongoComments code will probably need to change to include a list of entries that failed to sync, and then skip any comment referring to those entries.

**Comment by megahirt** [comment]
I think keeping track of failed sync entries is probably overkill.  A failed sync on an entry doesn't necessarily mean that the entry doesn't exist (although it could mean that).  A better check could simply be to check if the entry exists in the target before adding comments that refer to that entry.  If the entry doesn't exist, skip creating the comment.
