### ISSUE TITLE
Rename pbuild.sh to build.sh

### ISSUE THREAD

**Issue by josephmyers** [sillsdev/LfMerge#297]

**Comment by rmunn** [comment]
In addition to renaming pbuild.sh, there are a few things in there that we can safely clean up, such as the code that looks for the `parallel` tool (now that we're only building for DbModel 7000072, there's no point in the added complexity of the `parallel` tool, and once we start building more DbModels there still won't be much point because we it will be better to run the build for one version at a time). So I'll take this opportunity to clean up the script a little more.
