### ISSUE TITLE
WARNING: syslog logging no longer available, logging to console instead

### ISSUE THREAD

**Issue by megahirt** [sillsdev/LfMerge#311]
This error:
`WARNING: syslog logging no longer available, logging to console instead`
Now appears in the LFMerge logs with every run.  LFMerge should properly log to STDOUT and not to syslog.

I don't know where in the code logging is being attempted to syslog.

**Comment by rmunn** [comment]
That's happening because `LFMERGE_LOGGING_DEST=syslog` is set in the environment. That was a temporary measure to provide some level of continuity. It's safe to remove the `LFMERGE_LOGGING_DEST` environment variable now, since logging now defaults to console only. Once that is done, then we can also remove the "syslog logging no longer available" error message.

**Comment by rmunn** [comment]
#326 will remove that "syslog logging no longer available" message and close out this issue.
